version: 2.1

# its a NODE JS application 
jobs: # now set the jobs stages

  build: #build jobs
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i #instaling the dependencies
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules

      - run: npm run lint #Linting is the process of running a program that analyses code for potential errors. 

  test: #test jobs
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze: #analyse jobs
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm install --save-dev jest@28.1.3
      - run: npm install --save-dev webpack-hot-middleware@2.25.1
      - run: npm install --save-dev cssnano@5.1.12
      - run: npm update path-parse --depth 3
      - run: npm update watchpack --depth
      - run: npm update glob-parent --depth 3
      - run: npm update mkdirp --depth 12
      - run: npm update minimist --depth 13
      - run: npm update cssnano-preset-default --depth 2
      - run: npm update eazy-logger --depth 2
      - run: npm update path-parse --depth 12
      - run: npm update socket.io-parser --depth 4
      - run: npm update postcss --depth 5
      - run: npm update browserslist --depth 5
      # - run: npm audit fix
      # - lets go


workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
